import { resolve } from 'path';
import { defineConfig } from 'vite';
import fs from 'fs'; // Need fs to read generated files
import path from 'path'; // Need path

// Function to find all generated material detail pages
const getMaterialDetailPages = () => {
  const materialsDataDir = path.join(__dirname, 'src', 'data', 'materials');
  const pages = {};
  try {
    if (fs.existsSync(materialsDataDir)) {
        const files = fs.readdirSync(materialsDataDir);
        files.forEach(file => {
            if (file.endsWith('.md') || file.endsWith('.json')) { // Check based on your data file type
                // Generate slug based on filename (consistent with build-content.js)
                let slugBase = file.endsWith('.md') ? path.basename(file, '.md') : path.basename(file, '.json');
                 // Basic slugify needed here if titles aren't reliable filenames
                const slug = slugBase.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '').replace(/--+/g, '-').replace(/^-+/, '').replace(/-+$/, '');

                const pageName = `materialDetail_${slug}`; // Unique key for Rollup
                const pagePath = `material-detail-${slug}.html`;
                // Check if the file was actually generated by build-content.js before adding
                if (fs.existsSync(resolve(__dirname, pagePath))) {
                    pages[pageName] = resolve(__dirname, pagePath);
                } else {
                     console.warn(`Build script did not generate expected file: ${pagePath}`);
                }

            }
        });
    }
  } catch (error) {
      console.error("Error reading material data files for Vite config:", error);
  }
  return pages;
};

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        // Core Pages
        main: resolve(__dirname, 'index.html'),
        about: resolve(__dirname, 'about.html'),
        services: resolve(__dirname, 'services.html'),
        portfolio: resolve(__dirname, 'portfolio.html'),
        contact: resolve(__dirname, 'contact.html'),

        // Design Tools Section
        designTools: resolve(__dirname, 'design-tools.html'),
        styleQuiz: resolve(__dirname, 'style-quiz.html'),
        moodBoard: resolve(__dirname, 'mood-board.html'),
        projectEstimator: resolve(__dirname, 'project-estimator.html'),

        // Style Quiz Results
        styleResultModern: resolve(__dirname, 'style-result-modern.html'),
        styleResultBoho: resolve(__dirname, 'style-result-boho.html'),
        styleResultMinimalist: resolve(__dirname, 'style-result-minimalist.html'),
        styleResultTraditional: resolve(__dirname, 'style-result-traditional.html'),

        // Materials Library (main page)
        materialsLibrary: resolve(__dirname, 'materials-library.html'),

        // Portfolio Detail Pages (List ALL you have)
        portfolioDetailModernApt: resolve(__dirname, 'portfolio-detail-modern-apt.html'),
        portfolioDetailLuxuryVilla: resolve(__dirname, 'portfolio-detail-luxury-villa.html'),
        portfolioDetailMinimalistStudio: resolve(__dirname, 'portfolio-detail-minimalist-studio.html'),
        portfolioDetailTraditionalHome: resolve(__dirname, 'portfolio-detail-traditional-home.html'),
        portfolioDetailBohoBedroom: resolve(__dirname, 'portfolio-detail-boho-bedroom.html'),
        portfolioDetailScandiLiving: resolve(__dirname, 'portfolio-detail-scandi-living.html'),

        // Dynamically add generated Material Detail Pages
        ...getMaterialDetailPages(),

      },
    },
  },
});