backend:
  name: github
  repo: KESPREME/neelkanth-interio # Ensure this is exactly correct
  branch: main # Ensure this is your deploy branch

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "materials"
    label: "Materials Library"
    folder: "src/data/materials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["hardware", "wallpaper", "pvc-panel", "panel", "tile"] }
      - { label: "Style/Finish", name: "style", widget: "select", options: ["matte-black", "brushed-brass", "polished-nickel", "geometric", "floral", "wood-look", "marble-look", "greenery", "other"], required: false }
      - { label: "Featured Image (Grid)", name: "image", widget: "image" }
      - { label: "Detail Page URL", name: "detailPage", widget: "string", hint: "e.g., /material-detail-orb-knob.html. Ensure this page exists!"}
      - { label: "Description", name: "description", widget: "markdown", required: false }
      - { label: "Specifications", name: "specs", widget: "list", required: false, fields: [
          { label: "Spec Name", name: "name", widget: "string"},
          { label: "Spec Value", name: "value", widget: "string"}
        ]}
      - { label: "Detail Gallery Images", name: "gallery", widget: "list", required: false, summary: "{{fields.alt}}", fields: [
           { label: "Image", name: "image", widget: "image"},
           { label: "Alt Text", name: "alt", widget: "string"}
         ] }